### ISSUE TITLE
Increase photo similarity percentage requirement.

### ISSUE THREAD

**Issue by Satoshiii-DCS** [FujiMakoto/twitter-saucenao#18]
I was surprised to see SauceBot reply to a post that had a low image similarity percentage on SauceNAO. It gave out the wrong sauce for the post unfortunately.

![InkedScreen Shot 2020-07-22 at 22 24 56_LI](https://user-images.githubusercontent.com/61380847/88186093-9cff0a80-cbe9-11ea-8516-d6a0eef4b9a7.jpg)

SauceNAO automatically hides low similarity results so maybe SauceBot can do the same,

**Comment by FujiMakoto** [comment]
We do have a minimum similarity set, but I agree it might be a bit too low.

Amusingly in this specific example it.. got the artist right, but apparently it's an entirely different set of works by them, lol.

I'll see about increasing the minimum similarity to 60 or so to help cut back on false positives. I don't want to set it too low, because sometimes it can return the correct results even if the similarity is a bit low (especially if there's cropping in the source image, or someone has plastered a watermark over it, etc.)

**Comment by FujiMakoto** [comment]
Here's an example where, even though the similarity was low, it still provided an accurate result:
`https://twitter.com/saucenaopls/status/1286020852132335618` (nsfw)

The similarity is lower because of the crop, but it's otherwise still useful.

This is why I try and keep it balanced around 50.0. Sometimes it can get it right, other times it's completely wrong, it's kind of hard to balance effectively.
