### ISSUE TITLE
Replies not working properly

### ISSUE THREAD

**Issue by Ereshkigal101** [FujiMakoto/twitter-saucenao#4]
Hey once again!
Just thought you'd like to know that for some reason, whenever someone mentions me, the bot decides to reply to that mention if it has an image. Is there any way to turn of replies if mentioned, or if they're using a specific word like "source?", "sauce?", etc?

Cause in the Config file, I currently have:
monitored_accounts: WaifusCentral
monitored_keyword: Sauce, Source

And it's still replying to people if they don't use those keywords D:

**Comment by FujiMakoto** [comment]
Hello!

I would probably avoid using "sauce" or other single word keywords. The main bot currently queries "sauce pls", so those two will likely conflict with each other. You could run one with "source pls" and "source please" as an alternative if you wanted, though!

I'll also add in an option to disable responding to mentions tonight, so you can have the bot only monitor specific accounts.

**Comment by FujiMakoto** [comment]
Also yeah, the reason your bot is replying to all of my comments is because you're querying "source," and the bot by default replies to comments saying "I found the source of this for you!", so it ends up getting looped there.

I'll hardcode the bot to never respond to the official saucenao account, and maybe look into implemented a hashtag like #sauce or something that will work as a global blacklist to prevent bots from combating each other.

**Comment by FujiMakoto** [comment]
@Ereshkigal101 I've added a configuration option in the latest commit to disable responding to mentions. Just add this to your `config.ini` file under the Twitter section,

```ini
disable_mentions: true
```

**Comment by Ereshkigal101** [comment]
Awesome, thank you so much! Thanks for all of the hard work :)
